package proyectofinalpoo;


import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.JOptionPane;


/**
 *
 * @author Aaron
 */
public class Principal extends javax.swing.JFrame {

    private String nombreJugador1 = "Jugador1";
    private String nombreJugador2 = "Jugador2";
    private Juego juego;
    private javax.swing.JLabel[] jlblCasillas;
    private Random random = new Random();
    
    public Principal() {
        initComponents();
        inicializarLabels();
        inicializarJuego();
        setMinimumSize(new Dimension(1300, 756));
        setSize(1300, 756);
        setLocationRelativeTo(null);
    }
    
    
    private void inicializarLabels() {
    jlblCasillas = new javax.swing.JLabel[12];
    jlblCasillas[0] = jlblInicio;
    jlblCasillas[1] = jlblCasilla2;
    jlblCasillas[2] = jlblCasilla3;
    jlblCasillas[3] = jlblCasilla4;
    jlblCasillas[4] = jlblCasilla5;
    jlblCasillas[5] = jlblCasilla6;
    jlblCasillas[6] = jlblCasilla7;
    jlblCasillas[7] = jlblCasilla8;
    jlblCasillas[8] = jlblCasilla9;
    jlblCasillas[9] = jlblCasilla10;
    jlblCasillas[10] = jlblCasilla11;
    jlblCasillas[11] = jlblCasilla12;
    }
    
    private void actualizarTablero() {
    // limpia todas las casillas
    for (int i = 0; i < jlblCasillas.length; i++) {
        if (i == 0) {
            jlblCasillas[i].setText("Inicio");
        } else {
            jlblCasillas[i].setText("Casilla " + i);
        }
    }

    // coloca jugadores
    for (Jugador j : juego.getJugadores()) {
        int pos = j.getPosicion();
        String nombre = j.getNombre().equals("Jugador 1") ? "(J1)" : "(J2)";
        String textoActual = jlblCasillas[pos].getText();
        jlblCasillas[pos].setText(textoActual + " " + nombre);
    }

    // actualizar puntajes y comodines
    jlblPuntosJ1.setText("Puntos: " + juego.getJugadores().get(0).getPuntos());
    jlblPuntosJ2.setText("Puntos: " + juego.getJugadores().get(1).getPuntos());
    jlblComodinJ1.setText("Comodines: " + juego.getJugadores().get(0).getComodines());
    jlblComodinJ2.setText("Comodines: " + juego.getJugadores().get(1).getComodines());
    
    }
    
    private void inicializarJuego() {
    juego = new Juego();
    actualizarTablero();
    }
    
    private void mostrarScore() {
    // obtiene los jugadores
    Jugador j1 = juego.getJugadores().get(0);
    Jugador j2 = juego.getJugadores().get(1);
    
    String resultado1 = j1.getNombre() + " puntos: " + j1.getPuntos() + " | Fallos: " + j1.getFallos();
    String resultado2 = j2.getNombre() + " puntos: " + j2.getPuntos() + " | Fallos: " + j2.getFallos();

    // determinar ganador y perdedor
    String primero, segundo;
    if (j1.getPuntos() >= j2.getPuntos()) {
        primero = "1er Puesto: " + j1.getNombre();
        segundo = "2do Puesto: " + j2.getNombre();
    } else {
        primero = "1er Puesto: " + j2.getNombre();
        segundo = "2do Puesto: " + j1.getNombre();
    }

    // actualiza los labels de score
    jlblResultado1.setText(resultado1);
    jlblResultado2.setText(resultado2);
    jlblPuntos1.setText(primero);
    jlblPuntos2.setText(segundo);

    // Cambiar a la pestaña Score
    jtblMonopolyPrincipal.setSelectedIndex(3); // Ajusta con el índice de tu pestaña Score
    
    //exporta al txt
    exportarEstadisticas();
    }
    
    //txt
    private void exportarEstadisticas() {
    try {
        FileWriter fw = new FileWriter("Estadisticas.txt");
        BufferedWriter bw = new BufferedWriter(fw);

        for (Jugador j : juego.getJugadores()) {
            bw.write("=====================================\n");
            bw.write("Jugador: " + j.getNombre() + "\n");
            bw.write("Puntaje: " + j.getPuntos() + "\n");
            bw.write("Fallos: " + j.getFallos() + "\n\n");
            bw.write(">>> Historial de preguntas:\n");

            for (RegistroPregunta r : j.getHistorial()) {
                bw.write(r.toString() + "\n");
            }
        }

        bw.close();
        fw.close();
        JOptionPane.showMessageDialog(null, "Estadísticas exportadas exitosamente en Estadisticas.txt");

    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al exportar estadísticas.");
    }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtblMonopolyPrincipal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtxtJ1 = new javax.swing.JTextField();
        jtxtJ2 = new javax.swing.JTextField();
        jbtnNombreConfirma = new javax.swing.JButton();
        jpanelMonopoly = new javax.swing.JPanel();
        jlblInicio = new javax.swing.JLabel();
        jlblCasilla2 = new javax.swing.JLabel();
        jlblCasilla3 = new javax.swing.JLabel();
        jlblCasilla4 = new javax.swing.JLabel();
        jlblCasilla5 = new javax.swing.JLabel();
        jlblCasilla6 = new javax.swing.JLabel();
        jlblCasilla8 = new javax.swing.JLabel();
        jlblCasilla9 = new javax.swing.JLabel();
        jlblCasilla10 = new javax.swing.JLabel();
        jlblCasilla7 = new javax.swing.JLabel();
        jlblCasilla12 = new javax.swing.JLabel();
        jlblCasilla11 = new javax.swing.JLabel();
        jpanelJ1 = new javax.swing.JPanel();
        jlblJ1 = new javax.swing.JLabel();
        jlblPuntosJ1 = new javax.swing.JLabel();
        jlblComodinJ1 = new javax.swing.JLabel();
        jpanelJ2 = new javax.swing.JPanel();
        jlblJ2 = new javax.swing.JLabel();
        jlblPuntosJ2 = new javax.swing.JLabel();
        jlblComodinJ2 = new javax.swing.JLabel();
        jlblNumeroDado = new javax.swing.JLabel();
        jbtnTirar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelScore = new javax.swing.JPanel();
        jlblPuntos1 = new javax.swing.JLabel();
        jlblResultado1 = new javax.swing.JLabel();
        jlblPuntos2 = new javax.swing.JLabel();
        jlblResultado2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("El juego consiste en varias preguntas que constaran de unos enciados donde estudiaremos \ntemas importantes como la suma, una operación básica que combina cantidades para obtener \nun total, y la resta, que consiste en encontrar la diferencia entre números. También \naprenderemos sobre la multiplicación, una forma rápida de sumar grupos iguales, y la división, \nque nos ayuda a repartir cantidades en partes equitativas. Además, exploraremos la \nfascinante historia del Perú, desde sus antiguas civilizaciones como los incas hasta su \ndesarrollo en la época colonial y republicana, conociendo sus grandes logros y desafíos. \nPor último, profundizaremos en la geografía peruana, analizando sus tres regiones naturales \ncosta, sierra y selva, sus recursos, climas y las principales ciudades que conforman este \ndiverso país. Estos temas nos darán una base sólida tanto en matemáticas como en el \nconocimiento de nuestro país.");
        jScrollPane1.setViewportView(jTextArea1);

        jtxtJ1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador1"));

        jtxtJ2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jugador2"));

        jbtnNombreConfirma.setText("Confirmar");
        jbtnNombreConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNombreConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jtxtJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jbtnNombreConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNombreConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jtblMonopolyPrincipal.addTab("Introduccion", jPanel1);

        jpanelMonopoly.setBackground(new java.awt.Color(102, 255, 255));

        jlblInicio.setBackground(new java.awt.Color(255, 153, 0));
        jlblInicio.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblInicio.setForeground(new java.awt.Color(255, 153, 102));
        jlblInicio.setText("Inicio");

        jlblCasilla2.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla2.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla2.setText("Casilla 2");

        jlblCasilla3.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla3.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla3.setText("Casilla 3");

        jlblCasilla4.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla4.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla4.setText("Casilla 4");

        jlblCasilla5.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla5.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla5.setText("Casilla 5");

        jlblCasilla6.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla6.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla6.setText("Casilla 6");

        jlblCasilla8.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla8.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla8.setText("Casilla 8");

        jlblCasilla9.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla9.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla9.setText("Casill 9");

        jlblCasilla10.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla10.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla10.setText("Casilla 10");

        jlblCasilla7.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla7.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla7.setText("Casilla 7");

        jlblCasilla12.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla12.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla12.setText("Casilla 12");

        jlblCasilla11.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        jlblCasilla11.setForeground(new java.awt.Color(255, 153, 102));
        jlblCasilla11.setText("Casilla 11");

        jpanelJ1.setBackground(new java.awt.Color(102, 255, 255));
        jpanelJ1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));

        jlblJ1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlblJ1.setForeground(new java.awt.Color(255, 82, 82));
        jlblJ1.setText("Jugador 1");

        jlblPuntosJ1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlblPuntosJ1.setText("Puntos: 0");

        jlblComodinJ1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlblComodinJ1.setText("Comodines: 0");

        javax.swing.GroupLayout jpanelJ1Layout = new javax.swing.GroupLayout(jpanelJ1);
        jpanelJ1.setLayout(jpanelJ1Layout);
        jpanelJ1Layout.setHorizontalGroup(
            jpanelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelJ1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpanelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblComodinJ1)
                    .addComponent(jlblPuntosJ1)
                    .addComponent(jlblJ1))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jpanelJ1Layout.setVerticalGroup(
            jpanelJ1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelJ1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlblJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblPuntosJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblComodinJ1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelJ2.setBackground(new java.awt.Color(102, 255, 255));
        jpanelJ2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));

        jlblJ2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlblJ2.setForeground(new java.awt.Color(68, 138, 255));
        jlblJ2.setText("Jugador 2");

        jlblPuntosJ2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlblPuntosJ2.setText("Puntos: 0");

        jlblComodinJ2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jlblComodinJ2.setText("Comodines: 0");

        javax.swing.GroupLayout jpanelJ2Layout = new javax.swing.GroupLayout(jpanelJ2);
        jpanelJ2.setLayout(jpanelJ2Layout);
        jpanelJ2Layout.setHorizontalGroup(
            jpanelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelJ2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpanelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblComodinJ2)
                    .addComponent(jlblPuntosJ2)
                    .addComponent(jlblJ2))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jpanelJ2Layout.setVerticalGroup(
            jpanelJ2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelJ2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlblJ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblPuntosJ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblComodinJ2))
        );

        jlblNumeroDado.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jlblNumeroDado.setText("1");

        jbtnTirar.setBackground(new java.awt.Color(118, 255, 3));
        jbtnTirar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jbtnTirar.setText("Tirar");
        jbtnTirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTirarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelMonopolyLayout = new javax.swing.GroupLayout(jpanelMonopoly);
        jpanelMonopoly.setLayout(jpanelMonopolyLayout);
        jpanelMonopolyLayout.setHorizontalGroup(
            jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMonopolyLayout.createSequentialGroup()
                .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelMonopolyLayout.createSequentialGroup()
                        .addGap(541, 541, 541)
                        .addComponent(jbtnTirar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelMonopolyLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jpanelJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpanelJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelMonopolyLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblCasilla10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblCasilla12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblCasilla11))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblCasilla9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblCasilla2))
                        .addGap(18, 18, 18)
                        .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCasilla3)
                            .addComponent(jlblCasilla8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblCasilla4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblCasilla5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblCasilla7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblCasilla6)))
                    .addGroup(jpanelMonopolyLayout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(jlblNumeroDado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        jpanelMonopolyLayout.setVerticalGroup(
            jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMonopolyLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpanelJ1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanelJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelMonopolyLayout.createSequentialGroup()
                        .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblCasilla4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jlblCasilla3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCasilla2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addComponent(jlblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblCasilla12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCasilla5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblCasilla11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCasilla6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelMonopolyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblCasilla7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCasilla8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCasilla9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCasilla10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblNumeroDado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnTirar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jtblMonopolyPrincipal.addTab("Monopoly", jpanelMonopoly);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1141, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        jtblMonopolyPrincipal.addTab("Correccion", jPanel3);

        jlblPuntos1.setText("Primer Puesto");

        jlblResultado1.setText("GANADOR");

        jlblPuntos2.setText("Segundo Puesto");

        jlblResultado2.setText("jLabel1");

        javax.swing.GroupLayout jPanelScoreLayout = new javax.swing.GroupLayout(jPanelScore);
        jPanelScore.setLayout(jPanelScoreLayout);
        jPanelScoreLayout.setHorizontalGroup(
            jPanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScoreLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(jPanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblPuntos1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jlblResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(67, 67, 67)
                .addGroup(jPanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPuntos2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanelScoreLayout.setVerticalGroup(
            jPanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScoreLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addGroup(jPanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblPuntos1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPuntos2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblResultado1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jlblResultado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jtblMonopolyPrincipal.addTab("Score", jPanelScore);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtblMonopolyPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtblMonopolyPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTirarActionPerformed
        Jugador jugadorActual = juego.getJugadorActual();
        int dado = juego.getDado().tirar();
        jlblNumeroDado.setText("" + dado);

        // mover al jugador
        jugadorActual.mover(dado, jlblCasillas.length);

        // revisar si cae en casilla 5 y otorgar comodín
        if (jugadorActual.getPosicion() == 5) {
            jugadorActual.ganarComodin();
            JOptionPane.showMessageDialog(this, jugadorActual.getNombre() + " ganó un comodín");
        }

        // mostrar pregunta
        boolean quiereUsarComodin = false;
        if (jugadorActual.getComodines() > 0) {
            int usar = JOptionPane.showConfirmDialog(this, jugadorActual.getNombre() + " ¿Quieres usar un comodín para saltar la pregunta?", "Usar comodín", JOptionPane.YES_NO_OPTION);
            if (usar == JOptionPane.YES_OPTION) {
                jugadorActual.usarComodin();
                quiereUsarComodin = true;
                JOptionPane.showMessageDialog(this, "Has usado un comodín. No respondes pregunta esta vez.");
            }
        }

        if (!quiereUsarComodin) {
            Pregunta.hacerPregunta(this, jugadorActual);
        }

        actualizarTablero();

        // revisar si algún jugador llegó a 100 puntos y mostrar Score
        int puntosJ1 = juego.getJugadores().get(0).getPuntos();
        int puntosJ2 = juego.getJugadores().get(1).getPuntos();
        if (puntosJ1 >= 100 || puntosJ2 >= 100) {
            
            
            mostrarScore();
        }

        juego.siguienteTurno();
    }//GEN-LAST:event_jbtnTirarActionPerformed

    private void jbtnNombreConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNombreConfirmaActionPerformed
        // TODO add your handling code here:
        String nombre1 = jtxtJ1.getText().trim();
        String nombre2 = jtxtJ2.getText().trim();

        if (nombre1.isEmpty() || nombre2.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor ingresa ambos nombres.");
            return;
        }

        // actualiza los labels con los nombres ingresados en el panel Monopoly
        jlblJ1.setText(nombre1);
        jlblJ2.setText(nombre2);

        // deshabilita los campos de texto y el botón para que no se cambie
        jtxtJ1.setEnabled(false);
        jtxtJ2.setEnabled(false);
        jbtnNombreConfirma.setEnabled(false);
    }//GEN-LAST:event_jbtnNombreConfirmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelScore;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtnNombreConfirma;
    private javax.swing.JButton jbtnTirar;
    private javax.swing.JLabel jlblCasilla10;
    private javax.swing.JLabel jlblCasilla11;
    private javax.swing.JLabel jlblCasilla12;
    private javax.swing.JLabel jlblCasilla2;
    private javax.swing.JLabel jlblCasilla3;
    private javax.swing.JLabel jlblCasilla4;
    private javax.swing.JLabel jlblCasilla5;
    private javax.swing.JLabel jlblCasilla6;
    private javax.swing.JLabel jlblCasilla7;
    private javax.swing.JLabel jlblCasilla8;
    private javax.swing.JLabel jlblCasilla9;
    private javax.swing.JLabel jlblComodinJ1;
    private javax.swing.JLabel jlblComodinJ2;
    private javax.swing.JLabel jlblInicio;
    private javax.swing.JLabel jlblJ1;
    private javax.swing.JLabel jlblJ2;
    private javax.swing.JLabel jlblNumeroDado;
    private javax.swing.JLabel jlblPuntos1;
    private javax.swing.JLabel jlblPuntos2;
    private javax.swing.JLabel jlblPuntosJ1;
    private javax.swing.JLabel jlblPuntosJ2;
    private javax.swing.JLabel jlblResultado1;
    private javax.swing.JLabel jlblResultado2;
    private javax.swing.JPanel jpanelJ1;
    private javax.swing.JPanel jpanelJ2;
    private javax.swing.JPanel jpanelMonopoly;
    private javax.swing.JTabbedPane jtblMonopolyPrincipal;
    private javax.swing.JTextField jtxtJ1;
    private javax.swing.JTextField jtxtJ2;
    // End of variables declaration//GEN-END:variables
}
